### ISSUE TITLE
too complicated

### ISSUE THREAD

**Issue by mrzhqiang** [playframework/play-websocket-java#102]
It is too complicated, Not suitable for learning websocket.

**Comment by marcospereira** [comment]
Hello @mrzhqiang,

Our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

You can also see more information about in our documentation here: https://www.playframework.com/documentation/2.7.x/JavaWebSockets

Best.
