### ISSUE TITLE
Websocket / Actor integration is lossy

### ISSUE THREAD

**Issue by wsargent** [playframework/play-websocket-java#46]
Because there is no backpressure involved in this implementation, it's possible to lose Websocket packets coming in when using Actors directly.

playframework/playframework#6246

Should refactor code to be in line with http://doc.akka.io/docs/akka/current/java/stream/stream-integrations.html to prevent this or at least make it clear in the documentation.

**Comment by Flo354** [comment]
Hi,

I am not sure to understand what you mean with "no backpressure involved", so I don't really understand what's wrong with akka actors.

Could you elaborate?

**Comment by wsargent** [comment]
@Flo354 please see https://github.com/playframework/playframework/issues/6246

**Comment by Flo354** [comment]
Thanks, I understand better now.
Should I move on now? Because I saw this issue https://github.com/playframework/playframework/issues/7723
